### PR TITLE
Remove Psalm job

### PR DESCRIPTION
**Pull request by greg0ire**
We have decided to stop running two static analysers on our repositories, because of the extra maintenance it causes to us.

### CODE REVIEW

**Comment by stof** [comment]
If phpstan is the tool being kept, all repos should first migrate their prefixed annotations to `@phpstan*` instead of `@psalm-*` because both tools are silently ignoring invalid annotations using the prefix of the other tool instead of reporting errors (because maybe they are actually valid in the other tool). Projects need to use the prefix for a tool they actually use to have a reliable CI.

**Comment by greg0ire** [comment]
We think that's fine, and we'll test that with a search and replace of `psalm-` before merging this.

**Comment by greg0ire** [comment]
Yeah, thanks for pointing that out, it made us discuss it more in depth, and come to the conclusion that it would be nicer to try the change before merging this. This will be released as a major version, and projects that want to keep using Psalm can copy paste the code I'm removing.

**Review by SenseException — APPROVED** [review]
I too use both tools in my OS projects and always got covered by one of them when the other put a blind eye to an issue. If every Doctrine project is okay with dropping psalm, we don't need a split in two separate workflows, which would be an alternative.

Does it matter if the replacements of psalm-annotations happen after a merge? I believed that these annotations were compatible to each of the two tools.

**Comment by SenseException** [comment]
Okay, nevermind. I just saw #51 :sweat_smile:

**Comment by ostrolucky** [comment]
Where was the discussion about dropping Psalm?

**Comment by stof** [comment]
@SenseException valid annotations are compatible with both tools. But reporting of invalid annotations is different, and you want invalid annotations in your own code to be reported by the tool you use.

@ostrolucky probably at the gathering of part of the Doctrine team taking place these days.

**Comment by greg0ire** [comment]
@stof you're correct, it's a discussion we had with @derrabus @alcaeus @gromNan @beberlei @morozov . The reasons invoked were:
- additional maintenance burden incurred by having to fight 2 tools instead of one
- concerns about Psalm itself (how we sometimes have to wait for it to be compatible with newest versions of our dependencies)

**Comment by derrabus** [comment]
We need a rebase here. 🙂

**Review by alcaeus — APPROVED** [review]

**Comment by greg0ire** [comment]
@derrabus I believe that's addressed now, for the most part.

**Review by derrabus — APPROVED** [review]

**Pull request merged**
